### PR TITLE
add docsAsMarkdown option

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I don't have anything more to add now, waiting on feedback and help for everything marked as "TODO".

**Comment by derhuerst** [comment]
`hafas-rest-api` accepts any `hafas-client`-compatible API client, e.g. `vbb-hafas`. The problem is that

- `vbb-hafas` accepts more options than the basic `hafas-client`. To be able to parse these additional options from the HTTP request, `hafas-rest-api` exposes an option called `addHafasOpts`.
- `vbb-hafas` might give a different output (with specific constraints) than an uncustomized `hafas-client`. This means that the docs as hard-coded in your PR ("returns FPTF `1.2.0`") are not necessarily true.

What I think is arguably more complex, but more *correct*: Add an option `docsAsMarkdown` to `hafas-rest-api`, render them to HTML and serve via HTTP. What do you think?

**Comment by ghost** [comment]
I see the problem.
I'm not sure if I understand what you want to do: Should `docsAsMarkdown` return the documentation, so that vbb-rest can modify it somehow before serving it? Or should `docsAsMarkdown` be a way of overriding or adding documentation paragraphs?
Because the latter sounds like a good solution to me: Putting the default paragraphs of the documentation in an object, and giving the option for vbb-rest to override or add paragraphs.

After reading it again: Doesn't putting the whole documentation in db-rest / vbb-rest kind of defeat the point of this?

**Comment by derhuerst** [comment]
Just keep the `aboutPage` option, add an `docsAsMarkdown` option. `docsAsMarkdown` would be a string of Markdown that gets rendered to HTML and served at `/docs`.

**Comment by ghost** [comment]
Okay, but as I said, that would mean there would be version of the docs for every ...-rest package, which is what I want to avoid. In that case we could just leave it as it is now, linking to the GitHub page, as serving it as part of the rest server would not have any advantage.

**Comment by derhuerst** [comment]
> there would be version of the docs for every ...-rest package, which is what I want to avoid

Because `hafas-rest-api` accepts any `hafas-client`-compatible client and can't make make assumptions about which values/options it accepts, this is necessary.

> we could just leave it as it is now, linking to the GitHub page

- The API docs on GitHub can easily get behind or ahead of what's deployed at the REST endpoints.
- The API docs on GitHub can easily get lost, because of missing tags, force-pushes, etc.

This is why I highly appreciate hosting the docs at the same endpoint.

**Comment by derhuerst** [comment]
I've pushed the `docsAsMarkdown` option. Thanks for your effort anyways!

**Pull request closed without merging**
